services:
  - type: web
    name: mikaelson-family
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 